/** Set complex values as DOM properties, not string attributes. */
export type SfInputElement = HTMLElement & {
  modelValue?: string | number | boolean | FileList;
  label?: string;
  placeholder?: string;
  type?: string;
  icon?: string;
  hint?: string;
  error?: string;
  disabled?: boolean;
  required?: boolean;
  readonly?: boolean;
  name?: string;
  autocomplete?: string;
  inputmode?: string;
  min?: string | number;
  max?: string | number;
  step?: string | number;
  minlength?: number;
  maxlength?: number;
  pattern?: string;
  multiple?: boolean;
  accept?: string;
  capture?: string;
  list?: string;
  checkedValue?: string;
  size?: number;
  autofocus?: boolean;
  spellcheck?: boolean | string;
  enterkeyhint?: string;
  src?: string;
  alt?: string;
  width?: number;
  height?: number;
  form?: string;
  formaction?: string;
  formenctype?: string;
  formmethod?: string;
  formnovalidate?: boolean;
  formtarget?: string;
  dirname?: string;
  value?: string | number | boolean | FileList;
};
export declare const tagName: 'sf-input';
export declare function registerSfInput(registry?: CustomElementRegistry): CustomElementConstructor & { new(): SfInputElement };
