import { registerSfAccordion } from './SfAccordion.js';
import { registerSfAdaptedCards } from './SfAdaptedCards.js';
import { registerSfAlert } from './SfAlert.js';
import { registerSfAvatar } from './SfAvatar.js';
import { registerSfBadge } from './SfBadge.js';
import { registerSfBarChart } from './SfBarChart.js';
import { registerSfBottomNav } from './SfBottomNav.js';
import { registerSfBreadcrumbs } from './SfBreadcrumbs.js';
import { registerSfButton } from './SfButton.js';
import { registerSfButtonGroup } from './SfButtonGroup.js';
import { registerSfCalendar } from './SfCalendar.js';
import { registerSfCheckbox } from './SfCheckbox.js';
import { registerSfClock } from './SfClock.js';
import { registerSfDial } from './SfDial.js';
import { registerSfDivider } from './SfDivider.js';
import { registerSfDonutChart } from './SfDonutChart.js';
import { registerSfDrawer } from './SfDrawer.js';
import { registerSfDropdown } from './SfDropdown.js';
import { registerSfElement } from './SfElement.js';
import { registerSfEmptyState } from './SfEmptyState.js';
import { registerSfFab } from './SfFab.js';
import { registerSfFileUpload } from './SfFileUpload.js';
import { registerSfIcon } from './SfIcon.js';
import { registerSfIconButton } from './SfIconButton.js';
import { registerSfInput } from './SfInput.js';
import { registerSfListCard } from './SfListCard.js';
import { registerSfMediaPlayer } from './SfMediaPlayer.js';
import { registerSfMetricPanel } from './SfMetricPanel.js';
import { registerSfMixer } from './SfMixer.js';
import { registerSfModal } from './SfModal.js';
import { registerSfNavList } from './SfNavList.js';
import { registerSfNotification } from './SfNotification.js';
import { registerSfPagination } from './SfPagination.js';
import { registerSfProfileCard } from './SfProfileCard.js';
import { registerSfProgress } from './SfProgress.js';
import { registerSfRadioGroup } from './SfRadioGroup.js';
import { registerSfRating } from './SfRating.js';
import { registerSfSegmented } from './SfSegmented.js';
import { registerSfSelect } from './SfSelect.js';
import { registerSfSkeleton } from './SfSkeleton.js';
import { registerSfSlider } from './SfSlider.js';
import { registerSfSpinner } from './SfSpinner.js';
import { registerSfStatCard } from './SfStatCard.js';
import { registerSfStepper } from './SfStepper.js';
import { registerSfSurface } from './SfSurface.js';
import { registerSfSwitch } from './SfSwitch.js';
import { registerSfTable } from './SfTable.js';
import { registerSfTabs } from './SfTabs.js';
import { registerSfTextarea } from './SfTextarea.js';
import { registerSfTimeline } from './SfTimeline.js';
import { registerSfToast } from './SfToast.js';
import { registerSfTooltip } from './SfTooltip.js';
import { registerSfWorkflow } from './SfWorkflow.js';

/** Register all 53 custom elements once. Import one registration module for a smaller bundle. */
export function registerSoftformElements(registry = globalThis.customElements) {
  registerSfAccordion(registry);
  registerSfAdaptedCards(registry);
  registerSfAlert(registry);
  registerSfAvatar(registry);
  registerSfBadge(registry);
  registerSfBarChart(registry);
  registerSfBottomNav(registry);
  registerSfBreadcrumbs(registry);
  registerSfButton(registry);
  registerSfButtonGroup(registry);
  registerSfCalendar(registry);
  registerSfCheckbox(registry);
  registerSfClock(registry);
  registerSfDial(registry);
  registerSfDivider(registry);
  registerSfDonutChart(registry);
  registerSfDrawer(registry);
  registerSfDropdown(registry);
  registerSfElement(registry);
  registerSfEmptyState(registry);
  registerSfFab(registry);
  registerSfFileUpload(registry);
  registerSfIcon(registry);
  registerSfIconButton(registry);
  registerSfInput(registry);
  registerSfListCard(registry);
  registerSfMediaPlayer(registry);
  registerSfMetricPanel(registry);
  registerSfMixer(registry);
  registerSfModal(registry);
  registerSfNavList(registry);
  registerSfNotification(registry);
  registerSfPagination(registry);
  registerSfProfileCard(registry);
  registerSfProgress(registry);
  registerSfRadioGroup(registry);
  registerSfRating(registry);
  registerSfSegmented(registry);
  registerSfSelect(registry);
  registerSfSkeleton(registry);
  registerSfSlider(registry);
  registerSfSpinner(registry);
  registerSfStatCard(registry);
  registerSfStepper(registry);
  registerSfSurface(registry);
  registerSfSwitch(registry);
  registerSfTable(registry);
  registerSfTabs(registry);
  registerSfTextarea(registry);
  registerSfTimeline(registry);
  registerSfToast(registry);
  registerSfTooltip(registry);
  registerSfWorkflow(registry);
  return registry;
}

export { registerSfAccordion, registerSfAdaptedCards, registerSfAlert, registerSfAvatar, registerSfBadge, registerSfBarChart, registerSfBottomNav, registerSfBreadcrumbs, registerSfButton, registerSfButtonGroup, registerSfCalendar, registerSfCheckbox, registerSfClock, registerSfDial, registerSfDivider, registerSfDonutChart, registerSfDrawer, registerSfDropdown, registerSfElement, registerSfEmptyState, registerSfFab, registerSfFileUpload, registerSfIcon, registerSfIconButton, registerSfInput, registerSfListCard, registerSfMediaPlayer, registerSfMetricPanel, registerSfMixer, registerSfModal, registerSfNavList, registerSfNotification, registerSfPagination, registerSfProfileCard, registerSfProgress, registerSfRadioGroup, registerSfRating, registerSfSegmented, registerSfSelect, registerSfSkeleton, registerSfSlider, registerSfSpinner, registerSfStatCard, registerSfStepper, registerSfSurface, registerSfSwitch, registerSfTable, registerSfTabs, registerSfTextarea, registerSfTimeline, registerSfToast, registerSfTooltip, registerSfWorkflow };
