import { ADAPTER_KEY, defaultRegistry } from './adapters.js';
import SfElement from './components/SfElement.vue';
import SfIcon from './components/SfIcon.vue';
import SfSurface from './components/SfSurface.vue';
import SfBadge from './components/SfBadge.vue';
import SfAvatar from './components/SfAvatar.vue';
import SfDivider from './components/SfDivider.vue';
import SfSkeleton from './components/SfSkeleton.vue';
import SfSpinner from './components/SfSpinner.vue';
import SfButton from './components/SfButton.vue';
import SfIconButton from './components/SfIconButton.vue';
import SfButtonGroup from './components/SfButtonGroup.vue';
import SfFab from './components/SfFab.vue';
import SfInput from './components/SfInput.vue';
import SfTextarea from './components/SfTextarea.vue';
import SfSelect from './components/SfSelect.vue';
import SfCheckbox from './components/SfCheckbox.vue';
import SfRadioGroup from './components/SfRadioGroup.vue';
import SfSwitch from './components/SfSwitch.vue';
import SfSlider from './components/SfSlider.vue';
import SfStepper from './components/SfStepper.vue';
import SfDial from './components/SfDial.vue';
import SfRating from './components/SfRating.vue';
import SfFileUpload from './components/SfFileUpload.vue';
import SfTabs from './components/SfTabs.vue';
import SfSegmented from './components/SfSegmented.vue';
import SfBreadcrumbs from './components/SfBreadcrumbs.vue';
import SfPagination from './components/SfPagination.vue';
import SfNavList from './components/SfNavList.vue';
import SfBottomNav from './components/SfBottomNav.vue';
import SfAccordion from './components/SfAccordion.vue';
import SfAlert from './components/SfAlert.vue';
import SfToast from './components/SfToast.vue';
import SfProgress from './components/SfProgress.vue';
import SfEmptyState from './components/SfEmptyState.vue';
import SfTooltip from './components/SfTooltip.vue';
import SfStatCard from './components/SfStatCard.vue';
import SfBarChart from './components/SfBarChart.vue';
import SfDonutChart from './components/SfDonutChart.vue';
import SfTable from './components/SfTable.vue';
import SfTimeline from './components/SfTimeline.vue';
import SfCalendar from './components/SfCalendar.vue';
import SfNotification from './components/SfNotification.vue';
import SfProfileCard from './components/SfProfileCard.vue';
import SfMetricPanel from './components/SfMetricPanel.vue';
import SfMixer from './components/SfMixer.vue';
import SfWorkflow from './components/SfWorkflow.vue';
import SfListCard from './components/SfListCard.vue';
import SfClock from './components/SfClock.vue';
import SfMediaPlayer from './components/SfMediaPlayer.vue';
import SfModal from './components/SfModal.vue';
import SfDrawer from './components/SfDrawer.vue';
import SfDropdown from './components/SfDropdown.vue';
import SfAdaptedCards from './components/SfAdaptedCards.vue';

export { SfElement, SfIcon, SfSurface, SfBadge, SfAvatar, SfDivider, SfSkeleton, SfSpinner, SfButton, SfIconButton, SfButtonGroup, SfFab, SfInput, SfTextarea, SfSelect, SfCheckbox, SfRadioGroup, SfSwitch, SfSlider, SfStepper, SfDial, SfRating, SfFileUpload, SfTabs, SfSegmented, SfBreadcrumbs, SfPagination, SfNavList, SfBottomNav, SfAccordion, SfAlert, SfToast, SfProgress, SfEmptyState, SfTooltip, SfStatCard, SfBarChart, SfDonutChart, SfTable, SfTimeline, SfCalendar, SfNotification, SfProfileCard, SfMetricPanel, SfMixer, SfWorkflow, SfListCard, SfClock, SfMediaPlayer, SfModal, SfDrawer, SfDropdown, SfAdaptedCards };
export { ADAPTER_KEY, NotificationAdapter, RestNotificationAdapter, GraphQLNotificationAdapter, LegacyNotificationAdapter, AdapterRegistry, createAdapterRegistry, validateCards, defaultRegistry } from './adapters.js';
export const SoftformPlugin = { install(app, options = {}) {
  for (const component of [SfElement, SfIcon, SfSurface, SfBadge, SfAvatar, SfDivider, SfSkeleton, SfSpinner, SfButton, SfIconButton, SfButtonGroup, SfFab, SfInput, SfTextarea, SfSelect, SfCheckbox, SfRadioGroup, SfSwitch, SfSlider, SfStepper, SfDial, SfRating, SfFileUpload, SfTabs, SfSegmented, SfBreadcrumbs, SfPagination, SfNavList, SfBottomNav, SfAccordion, SfAlert, SfToast, SfProgress, SfEmptyState, SfTooltip, SfStatCard, SfBarChart, SfDonutChart, SfTable, SfTimeline, SfCalendar, SfNotification, SfProfileCard, SfMetricPanel, SfMixer, SfWorkflow, SfListCard, SfClock, SfMediaPlayer, SfModal, SfDrawer, SfDropdown, SfAdaptedCards]) app.component(component.name, component);
  app.provide(ADAPTER_KEY, options.registry || defaultRegistry);
} };
